function CommunityDetail({
      community,
        onBack,
          onJoin,
          }) {
            if (!community) return null;

              return (
                  <div
                        style={{
                                maxWidth: "700px",
                                        margin: "0 auto",
                                                padding: "20px",
                                                      }}
                                                          >
                                                                <button
                                                                        onClick={onBack}
                                                                                style={{
                                                                                          marginBottom: "20px",
                                                                                                    padding: "10px 16px",
                                                                                                              borderRadius: "10px",
                                                                                                                        border: "none",
                                                                                                                                  cursor: "pointer",
                                                                                                                                          }}
                                                                                                                                                >
                                                                                                                                                        ← Back
                                                                                                                                                              </button>

                                                                                                                                                                    <div
                                                                                                                                                                            style={{
                                                                                                                                                                                      height: "180px",
                                                                                                                                                                                                borderRadius: "18px",
                                                                                                                                                                                                          background:
                                                                                                                                                                                                                      "linear-gradient(135deg,#7c3aed,#5b21b6,#312e81)",
                                                                                                                                                                                                                                marginBottom: "20px",
                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                    <div style={{ textAlign: "center" }}>
                                                                                                                                                                                                                                                            <div style={{ fontSize: "64px" }}>
                                                                                                                                                                                                                                                                      {community.icon}
                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                      <h1>{community.name}</h1>

                                                                                                                                                                                                                                                                                              <p>{community.description}</p>

                                                                                                                                                                                                                                                                                                      <h3>
                                                                                                                                                                                                                                                                                                                {community.members.toLocaleString()} Members
                                                                                                                                                                                                                                                                                                                        </h3>

                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                          onClick={onJoin}
                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                marginTop: "10px",
                                                                                                                                                                                                                                                                                                                                                                            padding: "12px 26px",
                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "999px",
                                                                                                                                                                                                                                                                                                                                                                                                    border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                background: "#7c3aed",
                                                                                                                                                                                                                                                                                                                                                                                                                            color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                        fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                                    cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                + Join Community
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <hr style={{ margin: "30px 0" }} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2>About</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Welcome to the {community.name} community.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                This is where members will be able to share
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        posts, ideas, discussions, photos, and much
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                more.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <hr style={{ margin: "30px 0" }} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2>Community Feed</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>🚧 Community feed coming soon.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default CommunityDetail;
