import { useState } from "react";
import PostService from "../services/posts/PostService";
import MediaService from "../services/posts/MediaService";
import "../styles/login.css";

function CreatePost({ onBack }) {
  const [content, setContent] = useState("");
    const [imageFile, setImageFile] = useState(null);
      const [previewUrl, setPreviewUrl] = useState("");
        const [posting, setPosting] = useState(false);

          function handleImageChange(e) {
              const file = e.target.files[0];

                  if (!file) return;

                      setImageFile(file);
                          setPreviewUrl(URL.createObjectURL(file));
                            }

                              async function handlePost() {
                                  if (!content.trim() && !imageFile) {
                                        alert("Please add a caption or choose a photo.");
                                              return;
                                                  }

                                                      try {
                                                            setPosting(true);

                                                                  // Create the post first
                                                                        const post = await PostService.createPost(content);

                                                                              // Upload image if one was selected
                                                                                    if (imageFile) {
                                                                                            const mediaUrl = await MediaService.uploadImage(imageFile);

                                                                                            await MediaService.attachMedia({
                                                                                                  postId: post.id,
                                                                                                    mediaUrl,
                                                                                                      mediaType: "image",
                                                                                                        sortOrder: 0,
                                                                                                        });
                                                                                            
                                                                                                                                                          }

                                                                                                                                                                alert("Post created successfully!");

                                                                                                                                                                      setContent("");
                                                                                                                                                                            setImageFile(null);
                                                                                                                                                                                  setPreviewUrl("");

                                                                                                                                                                                        onBack();

                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                  alert(error.message);
                                                                                                                                                                                                      } finally {
                                                                                                                                                                                                            setPosting(false);
                                                                                                                                                                                                                }
                                                                                                                                                                                                                  }

                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                        <div className="login-screen">

                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                      className="secondary"
                                                                                                                                                                                                                                              onClick={onBack}
                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                            ← Back
                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                        <h1>✨ Be Creative</h1>

                                                                                                                                                                                                                                                                              <p
                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                color: "#bbbbbb",
                                                                                                                                                                                                                                                                                                          marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                Share a thought, a photo, a story, or something that inspires others.
                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                            <textarea
                                                                                                                                                                                                                                                                                                                                                    value={content}
                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setContent(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                    rows={6}
                                                                                                                                                                                                                                                                                                                                                                            placeholder="What's on your mind?"
                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                              width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                        maxWidth: "500px",
                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                resize: "vertical",
                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="file"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              accept="image/*"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleImageChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {previewUrl && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    src={previewUrl}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alt="Preview"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                maxWidth: "500px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={handlePost}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={posting}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: "24px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {posting ? "Creating..." : "🚀 Start Creating"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default CreatePost;