import { useState } from "react";
import CommunityService from "../services/community/CommunityService";

function CreateCommunity({ onBack }) {
  const [name, setName] = useState("");
    const [description, setDescription] = useState("");
      const [icon, setIcon] = useState("🏘️");
        const [privacy, setPrivacy] = useState("public");
        async function handleCreateCommunity() {
              try {
                  await CommunityService.createCommunity({
                        name,
                              description,
                                    icon,
                                       visibility: privacy,
                                              });

                                                  alert("Community created successfully!");

                                                      setName("");
                                                          setDescription("");
                                                              setIcon("🏘️");
                                                                  setPrivacy("public");

                                                                      if (onBack) {
                                                                            onBack();
                                                                                }
                                                                                  } catch (err) {
                                                                                      console.error(err);
                                                                                          alert(err.message || "Failed to create community.");
                                                                                            }
                                                                                            }

          return (
              <div
                    style={{
                            maxWidth: "700px",
                                    margin: "0 auto",
                                            padding: "20px",
                                                  }}
                                                      >
                                                            <button
                                                                    onClick={onBack}
                                                                            style={{
                                                                                      marginBottom: "20px",
                                                                                                padding: "10px 16px",
                                                                                                          borderRadius: "10px",
                                                                                                                    border: "none",
                                                                                                                              cursor: "pointer",
                                                                                                                                      }}
                                                                                                                                            >
                                                                                                                                                    ← Back
                                                                                                                                                          </button>

                                                                                                                                                                <h1>Create Community</h1>

                                                                                                                                                                      <p>Create a new community and invite others to join.</p>

                                                                                                                                                                            <div style={{ marginTop: "24px" }}>
                                                                                                                                                                                    <label>Community Name</label>

                                                                                                                                                                                            <input
                                                                                                                                                                                                      type="text"
                                                                                                                                                                                                                value={name}
                                                                                                                                                                                                                          onChange={(e) => setName(e.target.value)}
                                                                                                                                                                                                                                    placeholder="Enter community name..."
                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                      padding: "12px",
                                                                                                                                                                                                                                                                                  marginTop: "8px",
                                                                                                                                                                                                                                                                                              marginBottom: "20px",
                                                                                                                                                                                                                                                                                                          borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                    <label>Description</label>

                                                                                                                                                                                                                                                                                                                                            <textarea
                                                                                                                                                                                                                                                                                                                                                      value={description}
                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setDescription(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                          placeholder="Tell people what your community is about..."
                                                                                                                                                                                                                                                                                                                                                                                    rows={5}
                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                      padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                              marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label>Community Icon</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={icon}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setIcon(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    maxLength={2}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginBottom: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label>Privacy</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ marginTop: "10px", marginBottom: "24px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="radio"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value="public"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            checked={privacy === "public"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={() => setPrivacy("public")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Public
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <br />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="radio"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value="private"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      checked={privacy === "private"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={() => setPrivacy("private")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Private
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={handleCreateCommunity}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: "#7c3aed",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Create Community
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default CreateCommunity;