import { useEffect, useState } from "react";
import PostService from "../services/posts/PostService";
import LikeService from "../services/posts/LikeService";
import "../styles/login.css";

function Feed({ onBack, onCreatePost }) {
  const [posts, setPosts] = useState([]);
    const [loading, setLoading] = useState(true);

      useEffect(() => {
          loadFeed();
            }, []);

              async function loadFeed() {
                  try {
                        const data = await PostService.getFeed();

                              const feed = await Promise.all(
                                      data.map(async (post) => ({
                                                ...post,
                                                          liked: await LikeService.isLiked(post.id),
                                                                    likes: await LikeService.getLikeCount(post.id),
                                                                            }))
                                                                                  );

                                                                                        setPosts(feed);
                                                                                            } catch (error) {
                                                                                                  alert(error.message);
                                                                                                      } finally {
                                                                                                            setLoading(false);
                                                                                                                }
                                                                                                                  }

                                                                                                                    async function handleLike(postId) {
                                                                                                                        try {
                                                                                                                              const liked = await LikeService.toggleLike(postId);

                                                                                                                                    setPosts((current) =>
                                                                                                                                            current.map((post) => {
                                                                                                                                                      if (post.id !== postId) return post;

                                                                                                                                                                return {
                                                                                                                                                                            ...post,
                                                                                                                                                                                        liked,
                                                                                                                                                                                                    likes: liked ? post.likes + 1 : post.likes - 1,
                                                                                                                                                                                                              };
                                                                                                                                                                                                                      })
                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                      alert(error.message);
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                              function formatDate(date) {
                                                                                                                                                                                                                                                  return new Date(date).toLocaleString();
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                      if (loading) {
                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                <div className="login-screen">
                                                                                                                                                                                                                                                                        <h1>Loading Community...</h1>
                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                          <div className="login-screen">

                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                        className="secondary"
                                                                                                                                                                                                                                                                                                                onClick={onBack}
                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                              ← Back
                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                          <h1>Community</h1>

                                                                                                                                                                                                                                                                                                                                                <p className="tagline">
                                                                                                                                                                                                                                                                                                                                                        Discover what everyone is creating.
                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                            className="secondary home-card"
                                                                                                                                                                                                                                                                                                                                                                                    onClick={onCreatePost}
                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                  ✨ Be Creative
                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                              {posts.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="progress-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>No Posts Yet</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      Be the first person to inspire the community.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      posts.map((post) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={post.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="progress-card"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                textAlign: "left",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {post.profiles?.display_name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: "#4fc3f7",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      marginTop: "-10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              @{post.profiles?.username}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    whiteSpace: "pre-wrap",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginTop: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {post.content}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: "#999",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {formatDate(post.created_at)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="secondary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => handleLike(post.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {post.liked ? "❤️" : "🤍"} {post.likes}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default Feed;