import { useEffect, useState } from "react";
import FriendService from "../services/friend/FriendService";
import "../styles/login.css";

function FindFriends({ onBack }) {
  const [users, setUsers] = useState([]);
    const [search, setSearch] = useState("");
      const [loading, setLoading] = useState(true);

        useEffect(() => {
            loadUsers();
              }, []);

                useEffect(() => {
                    const timeout = setTimeout(() => {
                          loadUsers(search);
                              }, 250);

                                  return () => clearTimeout(timeout);
                                    }, [search]);

                                      async function loadUsers(searchText = "") {
                                          try {
                                                setLoading(true);
                                                      const data = await FriendService.searchUsers(searchText);
                                                            setUsers(data);
                                                                } catch (error) {
                                                                      alert(error.message);
                                                                          } finally {
                                                                                setLoading(false);
                                                                                    }
                                                                                      }

                                                                                        return (
                                                                                            <div className="login-screen">

                                                                                                  <button
                                                                                                          className="secondary"
                                                                                                                  onClick={onBack}
                                                                                                                        >
                                                                                                                                ← Back
                                                                                                                                      </button>

                                                                                                                                            <h1>Find Friends</h1>

                                                                                                                                                  <input
                                                                                                                                                          type="text"
                                                                                                                                                                  placeholder="Search by name or username..."
                                                                                                                                                                          value={search}
                                                                                                                                                                                  onChange={(e) => setSearch(e.target.value)}
                                                                                                                                                                                        />

                                                                                                                                                                                              {loading ? (
                                                                                                                                                                                                      <p>Searching...</p>
                                                                                                                                                                                                            ) : users.length === 0 ? (
                                                                                                                                                                                                                    <p>No users found.</p>
                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                  users.map((user) => (
                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                        key={user.id}
                                                                                                                                                                                                                                                                    className="progress-card"
                                                                                                                                                                                                                                                                                style={{ marginBottom: "18px" }}
                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                    display: "flex",
                                                                                                                                                                                                                                                                                                                                                    alignItems: "center",
                                                                                                                                                                                                                                                                                                                                                                    gap: "16px",
                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                            <div className="profile-photo-placeholder">
                                                                                                                                                                                                                                                                                                                                                                                                                            {user.avatar_url ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                              <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  src={user.avatar_url}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      alt={user.display_name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="profile-photo"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="profile-photo-icon">👤</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 style={{ margin: 0 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {user.display_name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: "#4fc3f7",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      marginTop: "4px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          @{user.username}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ marginTop: "18px" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        View Profile
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default FindFriends;