import supabase from "../../lib/supabase";

const CommunityService = {
  async getCurrentUser() {
      const {
            data: { user },
                } = await supabase.auth.getUser();

                    return user;
                      },

                        async createCommunity({
                            name,
                                description,
                                    icon,
                                        visibility = "public",
                                          }) {
                                              const user = await this.getCurrentUser();

                                                  if (!user) {
                                                        throw new Error("Please sign in first.");
                                                            }

                                                                const { data, error } = await supabase
                                                                      .from("communities")
                                                                            .insert({
                                                                                    name,
                                                                                            description,
                                                                                                    icon,
                                                                                                            visibility,
                                                                                                                    owner_id: user.id,
                                                                                                                          })
                                                                                                                                .select()
                                                                                                                                      .single();

                                                                                                                                          if (error) {
                                                                                                                                                throw error;
                                                                                                                                                    }

                                                                                                                                                        const { error: memberError } = await supabase
                                                                                                                                                              .from("community_members")
                                                                                                                                                                    .insert({
                                                                                                                                                                            community_id: data.id,
                                                                                                                                                                                    user_id: user.id,
                                                                                                                                                                                            role: "owner",
                                                                                                                                                                                                    status: "joined",
                                                                                                                                                                                                          });

                                                                                                                                                                                                              if (memberError) {
                                                                                                                                                                                                                    throw memberError;
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                            const { error: countError } = await supabase
                                                                                                                                                                                                                                  .from("communities")
                                                                                                                                                                                                                                        .update({
                                                                                                                                                                                                                                                member_count: 1,
                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                            .eq("id", data.id);

                                                                                                                                                                                                                                                                if (countError) {
                                                                                                                                                                                                                                                                      throw countError;
                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                              return data;
                                                                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                                                                  async getPublicCommunities() {
                                                                                                                                                                                                                                                                                      const { data, error } = await supabase
                                                                                                                                                                                                                                                                                            .from("communities")
                                                                                                                                                                                                                                                                                                  .select("*")
                                                                                                                                                                                                                                                                                                        .eq("visibility", "public")
                                                                                                                                                                                                                                                                                                              .order("created_at", { ascending: false });

                                                                                                                                                                                                                                                                                                                  if (error) {
                                                                                                                                                                                                                                                                                                                        throw error;
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                return data || [];
                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                    async getCommunityById(communityId) {
                                                                                                                                                                                                                                                                                                                                        const { data, error } = await supabase
                                                                                                                                                                                                                                                                                                                                              .from("communities")
                                                                                                                                                                                                                                                                                                                                                    .select("*")
                                                                                                                                                                                                                                                                                                                                                          .eq("id", communityId)
                                                                                                                                                                                                                                                                                                                                                                .single();

                                                                                                                                                                                                                                                                                                                                                                    if (error) {
                                                                                                                                                                                                                                                                                                                                                                          throw error;
                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                  return data;
                                                                                                                                                                                                                                                                                                                                                                                    },

                                                                                                                                                                                                                                                                                                                                                                                      async checkCommunityAccess(communityId) {
                                                                                                                                                                                                                                                                                                                                                                                          const user = await this.getCurrentUser();

                                                                                                                                                                                                                                                                                                                                                                                              const community = await this.getCommunityById(communityId);

                                                                                                                                                                                                                                                                                                                                                                                                  if (community.visibility !== "private") {
                                                                                                                                                                                                                                                                                                                                                                                                        return true;
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                if (!user) {
                                                                                                                                                                                                                                                                                                                                                                                                                      return false;
                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                              if (community.owner_id === user.id) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                            const { data, error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                  .from("community_members")
                                                                                                                                                                                                                                                                                                                                                                                                                                                        .select("id")
                                                                                                                                                                                                                                                                                                                                                                                                                                                              .eq("community_id", communityId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .eq("user_id", user.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .eq("status", "joined")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .maybeSingle();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          throw error;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return !!data;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      async getAccessibleCommunities() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const user = await this.getCurrentUser();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const publicCommunities = await this.getPublicCommunities();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!user) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return publicCommunities;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const { data: memberships, error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .from("community_members")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .select("community_id")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .eq("user_id", user.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .eq("status", "joined");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            throw error;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const communityIds = (memberships || []).map(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          (membership) => membership.community_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (communityIds.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return publicCommunities;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const { data: memberCommunities, error: communitiesError } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .from("communities")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .select("*")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .in("id", communityIds)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .order("created_at", { ascending: false });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (communitiesError) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  throw communitiesError;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const allCommunities = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ...publicCommunities,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ...(memberCommunities || []),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return allCommunities.filter(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    (community, index, communities) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            communities.findIndex((item) => item.id === community.id) === index
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default CommunityService;