import { useState } from "react";
import Welcome from "./pages/Welcome";
import Login from "./pages/Login";
import Register from "./pages/Register";
import ProfileSetup from "./pages/ProfileSetup";
import CommunityEntrance from "./pages/CommunityEntrance";
import Home from "./pages/Home";
import MyProfile from "./pages/MyProfile";
import EditProfile from "./pages/EditProfile";
import FindFriends from "./pages/FindFriends";
import PublicProfile from "./pages/PublicProfile";
import CreatePost from "./pages/CreatePost";
import Feed from "./pages/Feed";
import DiscoverCommunities from "./pages/DiscoverCommunities";
import CommunityDetail from "./pages/CommunityDetail";

function App() {
  const [screen, setScreen] = useState("welcome");
    const [selectedUserId, setSelectedUserId] = useState(null);
       const [selectedCommunity, setSelectedCommunity] = useState(null);

      switch (screen) {
          case "login":
                return (
                        <Login
                                  onRegister={() => setScreen("register")}
                                            onSuccess={(nextScreen) => setScreen(nextScreen)}
                                                    />
                                                          );

                                                              case "register":
                                                                    return (
                                                                            <Register
                                                                                      onBack={() => setScreen("login")}
                                                                                                onSuccess={() => setScreen("profile")}
                                                                                                        />
                                                                                                              );

                                                                                                                  case "profile":
                                                                                                                        return (
                                                                                                                                <ProfileSetup
                                                                                                                                          onContinue={() => setScreen("community")}
                                                                                                                                                  />
                                                                                                                                                        );

                                                                                                                                                            case "community":
                                                                                                                                                                  return (
                                                                                                                                                                          <CommunityEntrance
                                                                                                                                                                                    onEnter={() => setScreen("home")}
                                                                                                                                                                                            />
                                                                                                                                                                                                  );

                                                                                                                                                                                                      case "home":
                                                                                                                                                                                                            return (
                                                                                                                                                                                                                    <Home
                                                                                                                                                                                                                              onMyProfile={() => setScreen("myProfile")}
                                                                                                                                                                                                                                        onFindFriends={() => setScreen("findFriends")}
                                                                                                                                                                                                                                                  onCreatePost={() => setScreen("createPost")}
                                                                                                                                                                                                                                                            onCommunity={() => setScreen("feed")}
                                                                                                                                                                                                                                                                     onDiscoverCommunities={() => setScreen("discoverCommunities")}
                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                              case "myProfile":
                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                            <MyProfile
                                                                                                                                                                                                                                                                                                      onBack={() => setScreen("home")}
                                                                                                                                                                                                                                                                                                                onEditProfile={() => setScreen("editProfile")}
                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                  case "editProfile":
                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                <EditProfile
                                                                                                                                                                                                                                                                                                                                                          onBack={() => setScreen("myProfile")}
                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                            case "findFriends":
                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                          <FindFriends
                                                                                                                                                                                                                                                                                                                                                                                                    onBack={() => setScreen("home")}
                                                                                                                                                                                                                                                                                                                                                                                                              onViewProfile={(userId) => {
                                                                                                                                                                                                                                                                                                                                                                                                                          setSelectedUserId(userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                      setScreen("publicProfile");
                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  case "publicProfile":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <PublicProfile
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          userId={selectedUserId}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onBack={() => setScreen("findFriends")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      case "createPost":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <CreatePost
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onBack={() => setScreen("home")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case "feed":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Feed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onBack={() => setScreen("home")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onCreatePost={() => setScreen("createPost")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onViewProfile={(userId) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setSelectedUserId(userId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setScreen("publicProfile");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

case "discoverCommunities":
        return (
            <DiscoverCommunities
                  onBack={() => setScreen("home")}
                        onOpenCommunity={(community) => {
                                setSelectedCommunity(community);
                                        setScreen("communityDetail");
                                              }}
                                                  />
                                                    );
                                                    
case "communityDetail":
        return (
            <CommunityDetail
                  community={selectedCommunity}
                        onBack={() => setScreen("discoverCommunities")}
                              onJoin={() => {
                                      console.log(`Joined ${selectedCommunity?.name}`);
                                            }}
                                                />
                                                  );
                                                  

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Welcome
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onContinue={() => setScreen("login")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default App;