import { useState } from "react";
import Welcome from "./pages/Welcome";
import Login from "./pages/Login";
import Register from "./pages/Register";
import ProfileSetup from "./pages/ProfileSetup";
import CommunityEntrance from "./pages/CommunityEntrance";
import Home from "./pages/Home";
import MyProfile from "./pages/MyProfile";
import EditProfile from "./pages/EditProfile";
import FindFriends from "./pages/FindFriends";
import PublicProfile from "./pages/PublicProfile";
import CreatePost from "./pages/CreatePost";

function App() {
  const [screen, setScreen] = useState("welcome");
    const [selectedUserId, setSelectedUserId] = useState(null);

      switch (screen) {
          case "login":
                return (
                        <Login
                                  onRegister={() => setScreen("register")}
                                            onSuccess={(nextScreen) => setScreen(nextScreen)}
                                                    />
                                                          );

                                                              case "register":
                                                                    return (
                                                                            <Register
                                                                                      onBack={() => setScreen("login")}
                                                                                                onSuccess={() => setScreen("profile")}
                                                                                                        />
                                                                                                              );

                                                                                                                  case "profile":
                                                                                                                        return (
                                                                                                                                <ProfileSetup
                                                                                                                                          onContinue={() => setScreen("community")}
                                                                                                                                                  />
                                                                                                                                                        );

                                                                                                                                                            case "community":
                                                                                                                                                                  return (
                                                                                                                                                                          <CommunityEntrance
                                                                                                                                                                                    onEnter={() => setScreen("home")}
                                                                                                                                                                                            />
                                                                                                                                                                                                  );

                                                                                                                                                                                                      case "home":
                                                                                                                                                                                                            return (
                                                                                                                                                                                                                    <Home
                                                                                                                                                                                                                              onMyProfile={() => setScreen("myProfile")}
                                                                                                                                                                                                                                        onFindFriends={() => setScreen("findFriends")}
                                                                                                                                                                                                                                                  onCreatePost={() => setScreen("createPost")}
                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                    case "myProfile":
                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                  <MyProfile
                                                                                                                                                                                                                                                                                            onBack={() => setScreen("home")}
                                                                                                                                                                                                                                                                                                      onEditProfile={() => setScreen("editProfile")}
                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                        case "editProfile":
                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                      <EditProfile
                                                                                                                                                                                                                                                                                                                                                onBack={() => setScreen("myProfile")}
                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                  case "findFriends":
                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                <FindFriends
                                                                                                                                                                                                                                                                                                                                                                                          onBack={() => setScreen("home")}
                                                                                                                                                                                                                                                                                                                                                                                                    onViewProfile={(userId) => {
                                                                                                                                                                                                                                                                                                                                                                                                                setSelectedUserId(userId);
                                                                                                                                                                                                                                                                                                                                                                                                                            setScreen("publicProfile");
                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                        case "publicProfile":
                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <PublicProfile
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                userId={selectedUserId}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onBack={() => setScreen("findFriends")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case "createPost":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <CreatePost
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onBack={() => setScreen("home")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Welcome
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onContinue={() => setScreen("login")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default App;