create table public.trusted_six (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  trusted_user_id uuid not null references auth.users(id) on delete cascade,
  position smallint not null check (position between 1 and 6),
  created_at timestamptz not null default now(),

  constraint trusted_six_no_self
    check (user_id <> trusted_user_id),

  constraint trusted_six_unique_person
    unique (user_id, trusted_user_id),

  constraint trusted_six_unique_position
    unique (user_id, position)
);

alter table public.trusted_six enable row level security;

create policy "Authenticated users can view Trusted 6"
on public.trusted_six
for select
to authenticated
using (true);

create policy "Users can add to their own Trusted 6"
on public.trusted_six
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own Trusted 6"
on public.trusted_six
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can remove from their own Trusted 6"
on public.trusted_six
for delete
to authenticated
using (auth.uid() = user_id);
