-- 21st Social / Community Topics RLS
-- Adds row-level security policies to the existing community_topics table.
--
-- Topic access follows:
--   topic -> section -> community
--
-- Existing role/topic access and permission functions are reused.

begin;

alter table public.community_topics enable row level security;

drop policy if exists "Members can view permitted community topics"
  on public.community_topics;

  create policy "Members can view permitted community topics"
  on public.community_topics
  for select
  to authenticated
  using (
    exists (
        select 1
            from public.community_sections s
                where s.id = community_topics.section_id
                      and (
                              public.is_community_owner(s.community_id)

                                      or exists (
                                                select 1
                                                          from public.community_members cm
                                                                    join public.community_member_roles cmr
                                                                                on cmr.member_id = cm.id
                                                                                           and cmr.community_id = cm.community_id
                                                                                                     where cm.community_id = s.community_id
                                                                                                                 and cm.user_id = auth.uid()
                                                                                                                             and public.role_can_access_section(
                                                                                                                                           cmr.role_id,
                                                                                                                                                         s.id
                                                                                                                                                                     )
                                                                                                                                                                                 and public.role_can_access_topic(
                                                                                                                                                                                               cmr.role_id,
                                                                                                                                                                                                             community_topics.id
                                                                                                                                                                                                                         )
                                                                                                                                                                                                                                 )
                                                                                                                                                                                                                                       )
                                                                                                                                                                                                                                         )
                                                                                                                                                                                                                                         );

                                                                                                                                                                                                                                         drop policy if exists "Owners and permitted moderators can create topics"
                                                                                                                                                                                                                                           on public.community_topics;

                                                                                                                                                                                                                                           create policy "Owners and permitted moderators can create topics"
                                                                                                                                                                                                                                           on public.community_topics
                                                                                                                                                                                                                                           for insert
                                                                                                                                                                                                                                           to authenticated
                                                                                                                                                                                                                                           with check (
                                                                                                                                                                                                                                             exists (
                                                                                                                                                                                                                                                 select 1
                                                                                                                                                                                                                                                     from public.community_sections s
                                                                                                                                                                                                                                                         where s.id = community_topics.section_id
                                                                                                                                                                                                                                                               and public.has_community_permission(
                                                                                                                                                                                                                                                                       s.community_id,
                                                                                                                                                                                                                                                                               'manage_topics'
                                                                                                                                                                                                                                                                                     )
                                                                                                                                                                                                                                                                                       )
                                                                                                                                                                                                                                                                                       );

                                                                                                                                                                                                                                                                                       drop policy if exists "Owners and permitted moderators can update topics"
                                                                                                                                                                                                                                                                                         on public.community_topics;

                                                                                                                                                                                                                                                                                         create policy "Owners and permitted moderators can update topics"
                                                                                                                                                                                                                                                                                         on public.community_topics
                                                                                                                                                                                                                                                                                         for update
                                                                                                                                                                                                                                                                                         to authenticated
                                                                                                                                                                                                                                                                                         using (
                                                                                                                                                                                                                                                                                           exists (
                                                                                                                                                                                                                                                                                               select 1
                                                                                                                                                                                                                                                                                                   from public.community_sections s
                                                                                                                                                                                                                                                                                                       where s.id = community_topics.section_id
                                                                                                                                                                                                                                                                                                             and public.has_community_permission(
                                                                                                                                                                                                                                                                                                                     s.community_id,
                                                                                                                                                                                                                                                                                                                             'manage_topics'
                                                                                                                                                                                                                                                                                                                                   )
                                                                                                                                                                                                                                                                                                                                     )
                                                                                                                                                                                                                                                                                                                                     )
                                                                                                                                                                                                                                                                                                                                     with check (
                                                                                                                                                                                                                                                                                                                                       exists (
                                                                                                                                                                                                                                                                                                                                           select 1
                                                                                                                                                                                                                                                                                                                                               from public.community_sections s
                                                                                                                                                                                                                                                                                                                                                   where s.id = community_topics.section_id
                                                                                                                                                                                                                                                                                                                                                         and public.has_community_permission(
                                                                                                                                                                                                                                                                                                                                                                 s.community_id,
                                                                                                                                                                                                                                                                                                                                                                         'manage_topics'
                                                                                                                                                                                                                                                                                                                                                                               )
                                                                                                                                                                                                                                                                                                                                                                                 )
                                                                                                                                                                                                                                                                                                                                                                                 );

                                                                                                                                                                                                                                                                                                                                                                                 drop policy if exists "Owners and permitted moderators can delete topics"
                                                                                                                                                                                                                                                                                                                                                                                   on public.community_topics;

                                                                                                                                                                                                                                                                                                                                                                                   create policy "Owners and permitted moderators can delete topics"
                                                                                                                                                                                                                                                                                                                                                                                   on public.community_topics
                                                                                                                                                                                                                                                                                                                                                                                   for delete
                                                                                                                                                                                                                                                                                                                                                                                   to authenticated
                                                                                                                                                                                                                                                                                                                                                                                   using (
                                                                                                                                                                                                                                                                                                                                                                                     exists (
                                                                                                                                                                                                                                                                                                                                                                                         select 1
                                                                                                                                                                                                                                                                                                                                                                                             from public.community_sections s
                                                                                                                                                                                                                                                                                                                                                                                                 where s.id = community_topics.section_id
                                                                                                                                                                                                                                                                                                                                                                                                       and public.has_community_permission(
                                                                                                                                                                                                                                                                                                                                                                                                               s.community_id,
                                                                                                                                                                                                                                                                                                                                                                                                                       'manage_topics'
                                                                                                                                                                                                                                                                                                                                                                                                                             )
                                                                                                                                                                                                                                                                                                                                                                                                                               )
                                                                                                                                                                                                                                                                                                                                                                                                                               );

                                                                                                                                                                                                                                                                                                                                                                                                                               commit;